import Foundation
@testable import XCLogParser

func makeFakeBuildStep(title: String,
                       type: BuildStepType,
                       detailStepType: DetailStepType,
                       startTimestamp: Double,
                       fetchedFromCache: Bool) -> BuildStep {
    return BuildStep(type: type,
                     machineName: "",
                     buildIdentifier: "",
                     identifier: "",
                     parentIdentifier: "",
                     domain: "",
                     title: title,
                     signature: "",
                     startDate: "",
                     endDate: "",
                     startTimestamp: startTimestamp,
                     endTimestamp: 0,
                     duration: 0,
                     detailStepType: detailStepType,
                     buildStatus: "",
                     schema: "",
                     subSteps: [],
                     warningCount: 0,
                     errorCount: 0,
                     architecture: "",
                     documentURL: "",
                     warnings: nil,
                     errors: nil,
                     notes: nil,
                     swiftFunctionTimes: nil,
                     fetchedFromCache: fetchedFromCache,
                     compilationEndTimestamp: 0,
                     compilationDuration: 0,
                     clangTimeTraceFile: nil,
                     linkerStatistics: nil)
}
